import {
  Notification,
  NotificationScope,
  Project,
  ProjectStatus,
  Schedule,
  TaskStatus,
  User,
  UserRole,
  WbsTask,
} from './types';

const now = new Date();
const iso = (year: number, month: number, day: number, hour = 9) =>
  new Date(year, month - 1, day, hour, 0, 0).toISOString();
const thisMonth = now.getMonth() + 1;
const thisYear = now.getFullYear();

export const mockUsers: User[] = [
  {
    id: 'u-eng1',
    username: 'eng1',
    email: 'eng1@nise-gumo.local',
    display_name: '田中 太郎',
    role: UserRole.Engineer,
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=eng1',
    bio: 'フロントエンド担当。UIの細部を詰めています。',
    is_invisible: false,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
  {
    id: 'u-eng2',
    username: 'eng2',
    email: 'eng2@nise-gumo.local',
    display_name: '佐藤 花子',
    role: UserRole.Engineer,
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=eng2',
    bio: 'APIとテストを担当しています。',
    is_invisible: false,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
  {
    id: 'u-eng3',
    username: 'eng3',
    email: 'eng3@nise-gumo.local',
    display_name: '鈴木 次郎',
    role: UserRole.Engineer,
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=eng3',
    bio: '認証まわりを見ています。',
    is_invisible: true,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
  {
    id: 'u-pl1',
    username: 'pl1',
    email: 'pl1@nise-gumo.local',
    display_name: 'プロジェクトリーダー 1',
    role: UserRole.ProjectLeader,
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pl1',
    bio: 'NISE_GUMO全体の進行を管理しています。',
    is_invisible: false,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
  {
    id: 'u-admin1',
    username: 'admin1',
    email: 'admin1@nise-gumo.local',
    display_name: 'システム管理者 1',
    role: UserRole.SystemAdmin,
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin1',
    bio: 'アカウントと通知を管理しています。',
    is_invisible: false,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p-cloud',
    name: 'クラウド移行プロジェクト',
    description: '既存業務システムを段階的にクラウドへ移行する。',
    leader_id: 'u-pl1',
    start_date: iso(thisYear, thisMonth, 2),
    end_date: iso(thisYear, thisMonth + 2, 18),
    status: ProjectStatus.Active,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
  {
    id: 'p-mobile',
    name: 'モバイルアプリ開発',
    description: '進捗確認と通知返信をスマートフォンから扱えるようにする。',
    leader_id: 'u-pl1',
    start_date: iso(thisYear, thisMonth - 1, 20),
    end_date: iso(thisYear, thisMonth + 1, 28),
    status: ProjectStatus.Active,
    created_at: iso(thisYear, thisMonth - 1, 12),
    updated_at: iso(thisYear, thisMonth, 3),
  },
  {
    id: 'p-ai',
    name: 'AIチャットボット構築',
    description: '社内ナレッジ検索と問い合わせ一次対応を自動化する。',
    leader_id: 'u-pl1',
    start_date: iso(thisYear, thisMonth + 1, 4),
    end_date: iso(thisYear, thisMonth + 3, 10),
    status: ProjectStatus.Planning,
    created_at: iso(thisYear, thisMonth, 8),
    updated_at: iso(thisYear, thisMonth, 8),
  },
];

export const mockTasks: WbsTask[] = [
  {
    id: 't-1',
    project_id: 'p-cloud',
    title: '要件定義レビュー',
    description: '移行対象システムの要件と除外範囲を確認する。',
    assignee_id: 'u-eng1',
    start_date: iso(thisYear, thisMonth, 8),
    end_date: iso(thisYear, thisMonth, 14),
    progress: 70,
    status: TaskStatus.InProgress,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 8),
  },
  {
    id: 't-2',
    project_id: 'p-cloud',
    title: '認証API接続',
    description: 'モック認証からJWT認証へ差し替え可能な境界を整える。',
    assignee_id: 'u-eng2',
    start_date: iso(thisYear, thisMonth, 12),
    end_date: iso(thisYear, thisMonth, 21),
    progress: 45,
    status: TaskStatus.InProgress,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 8),
  },
  {
    id: 't-3',
    project_id: 'p-mobile',
    title: '通知返信UI',
    description: '管理者通知に対するはい/いいえ返信の画面を作る。',
    assignee_id: 'u-eng1',
    start_date: iso(thisYear, thisMonth, 16),
    end_date: iso(thisYear, thisMonth, 25),
    progress: 25,
    status: TaskStatus.InProgress,
    created_at: iso(thisYear, thisMonth - 1, 22),
    updated_at: iso(thisYear, thisMonth, 6),
  },
  {
    id: 't-4',
    project_id: 'p-ai',
    title: 'PoC設計',
    description: '検索対象データと回答品質の評価軸を定義する。',
    assignee_id: 'u-eng3',
    start_date: iso(thisYear, thisMonth + 1, 4),
    end_date: iso(thisYear, thisMonth + 1, 16),
    progress: 0,
    status: TaskStatus.NotStarted,
    created_at: iso(thisYear, thisMonth, 8),
    updated_at: iso(thisYear, thisMonth, 8),
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: 's-1',
    user_id: 'u-eng1',
    title: '11:00 定例MTG',
    description: 'クラウド移行の進捗確認',
    start_date: iso(thisYear, thisMonth, now.getDate(), 11),
    end_date: iso(thisYear, thisMonth, now.getDate(), 12),
    is_all_day: false,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
  {
    id: 's-2',
    user_id: 'u-eng1',
    title: 'レビュー準備',
    description: 'WBSと議事録を確認',
    start_date: iso(thisYear, thisMonth, Math.min(now.getDate() + 2, 28), 15),
    end_date: iso(thisYear, thisMonth, Math.min(now.getDate() + 2, 28), 16),
    is_all_day: false,
    created_at: iso(thisYear, thisMonth, 1),
    updated_at: iso(thisYear, thisMonth, 1),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n-1',
    title: '進捗確認',
    message: '本日中に担当WBSの進捗率を更新してください。',
    scope: NotificationScope.Global,
    options: ['はい', '後で対応'],
    created_by: 'u-admin1',
    created_at: iso(thisYear, thisMonth, now.getDate(), 9),
  },
];

export const projectMembers: Record<string, string[]> = {
  'p-cloud': ['u-pl1', 'u-eng1', 'u-eng2'],
  'p-mobile': ['u-pl1', 'u-eng1', 'u-eng3'],
  'p-ai': ['u-pl1', 'u-eng3'],
};
